#!/bin/sh

sudo dnf update --refresh -y
volta run --npm latest npm update --global
~/.venv/bin/pip install -Ur ./packages/base_pip.txt
~/.venv/bin/virtualenv --upgrade-embed-wheels
rustup update
cargo install-update -a
gup update
